# version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    # container_name: docker-course-nginx
    ports:
      - "8088:80"
  postgres:
    image: postgres:12
    # container_name: docker-course-postgres
    ports:
      - "5474:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:7
    # container_name: docker-course-redis
    ports:
      - "6379:6379"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5005:5000"
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    # container_name: docker-course-client
    ports:
      - "3007:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    # container_name: docker-course-worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - /app/node_modules
      - ./worker:/app
